import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
function formatDate(value) {
    return new Intl.DateTimeFormat("en-US", {
        month: "short",
        day: "numeric",
        year: "numeric",
        hour: "numeric",
        minute: "2-digit"
    }).format(new Date(value));
}
export function OrderDetailPage({ order, isLoading, isError, onBackToOrders, onContinueShopping }) {
    return (_jsx("main", { className: "gg-page", children: _jsxs("section", { className: "gg-panel", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-2", children: [_jsxs("div", { children: [_jsx("p", { className: "gg-kicker", children: "Order Detail" }), _jsx("h2", { className: "mt-2 font-display text-3xl text-white", children: order ? `Order #${order.id.slice(0, 8)}` : "Order" })] }), _jsxs("div", { className: "flex w-full flex-wrap gap-2 sm:w-auto", children: [_jsx("button", { className: "gg-btn-secondary max-sm:w-full", onClick: onBackToOrders, type: "button", children: "Back to Orders" }), _jsx("button", { className: "gg-btn-secondary max-sm:w-full", onClick: onContinueShopping, type: "button", children: "Shop Again" })] })] }), isLoading ? _jsx("p", { className: "mt-4 text-zinc-300", children: "Loading order detail..." }) : null, isError ? _jsx("p", { className: "mt-4 text-zinc-300", children: "Unable to load this order." }) : null, order && !isLoading && !isError ? (_jsxs(_Fragment, { children: [_jsxs("div", { className: "mt-4 rounded-xl border border-white/15 bg-black/30 p-4", children: [_jsxs("p", { className: "text-sm text-zinc-300", children: ["Placed: ", formatDate(order.createdAt)] }), _jsxs("p", { className: "text-sm text-zinc-300", children: ["Customer: ", order.customerName] }), _jsx("p", { className: "text-sm text-zinc-400", children: order.customerEmail })] }), _jsx("div", { className: "mt-5 space-y-3", children: order.items.map((item) => (_jsx("article", { className: "rounded-xl border border-white/10 bg-black/20 p-3", children: _jsxs("div", { className: "flex items-start justify-between gap-3", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-semibold text-white", children: item.productName }), _jsxs("p", { className: "text-sm text-zinc-300", children: [item.quantity, " x $", item.unitPrice.toFixed(2)] })] }), _jsxs("p", { className: "font-semibold text-zinc-100", children: ["$", item.lineTotal.toFixed(2)] })] }) }, item.id))) }), _jsxs("div", { className: "mt-5 border-t border-white/15 pt-4", children: [_jsxs("p", { className: "text-sm text-zinc-300", children: ["Total quantity: ", order.totalQuantity] }), _jsxs("p", { className: "text-lg font-semibold text-white", children: ["Total: $", order.totalAmount.toFixed(2)] })] }), _jsxs("div", { className: "mt-4 rounded-xl border border-white/10 bg-black/20 p-4 text-sm text-zinc-300", children: ["Need a change? Reach out before fulfillment and include order #", order.id.slice(0, 8), " for faster support."] })] })) : null] }) }));
}
